---
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
spec:
  cinder:
    template:
      cinderBackup:
        replicas: 0
      cinderBackups:
        $patch: replace
        cinder-backup-az0:
          customServiceConfig: |
            [DEFAULT]
            backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
            backup_ceph_conf = /etc/ceph/az0.conf
            backup_ceph_pool = backups
            backup_ceph_user = openstack
            storage_availability_zone = az0
          networkAttachments:
            - storage
            - ctlplane
          replicas: 1
          topologyRef:
            name: azone-node-affinity
        cinder-backup-az1:
          customServiceConfig: |
            [DEFAULT]
            backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
            backup_ceph_conf = /etc/ceph/az1.conf
            backup_ceph_pool = backups
            backup_ceph_user = openstack
            storage_availability_zone = az1
          networkAttachments:
            - storage
            - ctlplane
          replicas: 1
          topologyRef:
            name: bzone-node-affinity
        cinder-backup-az2:
          customServiceConfig: |
            [DEFAULT]
            backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
            backup_ceph_conf = /etc/ceph/az2.conf
            backup_ceph_pool = backups
            backup_ceph_user = openstack
            storage_availability_zone = az2
          networkAttachments:
            - storage
            - ctlplane
          replicas: 1
          topologyRef:
            name: czone-node-affinity
      cinderVolumes:
        $patch: replace
        ceph-az0:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = ceph-az0
            glance_api_servers = https://glance-az0-internal.openstack.svc:9292
            [ceph-az0]
            backend_availability_zone = az0
            volume_backend_name = ceph-az0
            volume_driver = cinder.volume.drivers.rbd.RBDDriver
            rbd_ceph_conf = /etc/ceph/az0.conf
            rbd_cluster_name = az0
            rbd_pool = volumes
            rbd_secret_uuid = CHANGE_TO_CEPH_FSID_AZ0
            rbd_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          topologyRef:
            name: azone-node-affinity
        ceph-az1:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = ceph-az1
            glance_api_servers = https://glance-az1-internal.openstack.svc:9292
            [ceph-az1]
            backend_availability_zone = az1
            volume_backend_name = ceph-az1
            volume_driver = cinder.volume.drivers.rbd.RBDDriver
            rbd_ceph_conf = /etc/ceph/az1.conf
            rbd_cluster_name = az1
            rbd_pool = volumes
            rbd_secret_uuid = CHANGE_TO_CEPH_FSID_AZ1
            rbd_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          topologyRef:
            name: bzone-node-affinity
        ceph-az2:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = ceph-az2
            glance_api_servers = https://glance-az2-internal.openstack.svc:9292
            [ceph-az2]
            backend_availability_zone = az2
            volume_backend_name = ceph-az2
            volume_driver = cinder.volume.drivers.rbd.RBDDriver
            rbd_ceph_conf = /etc/ceph/az2.conf
            rbd_cluster_name = az2
            rbd_pool = volumes
            rbd_secret_uuid = CHANGE_TO_CEPH_FSID_AZ2
            rbd_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          topologyRef:
            name: czone-node-affinity
  glance:
    template:
      glanceAPIs:
        $patch: replace
        default:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = az0:rbd,az1:rbd,az2:rbd
            enabled_import_methods = [web-download,copy-image,glance-direct]
            [glance_store]
            default_backend = az0
            [az0]
            rbd_store_ceph_conf = /etc/ceph/az0.conf
            rbd_store_pool = images
            rbd_store_user = openstack
            [az1]
            rbd_store_ceph_conf = /etc/ceph/az1.conf
            rbd_store_pool = images
            rbd_store_user = openstack
            [az2]
            rbd_store_ceph_conf = /etc/ceph/az2.conf
            rbd_store_pool = images
            rbd_store_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          replicas: 1
          type: split
        az0:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = az0:rbd
            [glance_store]
            default_backend = az0
            [az0]
            rbd_store_ceph_conf = /etc/ceph/az0.conf
            rbd_store_pool = images
            rbd_store_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          override:
            service:
              internal:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 172.17.0.81
                spec:
                  type: LoadBalancer
          replicas: 1
          topologyRef:
            name: azone-node-affinity
          type: edge
        az1:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = az0:rbd,az1:rbd
            [glance_store]
            default_backend = az1
            [az0]
            rbd_store_ceph_conf = /etc/ceph/az0.conf
            rbd_store_pool = images
            rbd_store_user = openstack
            [az1]
            rbd_store_ceph_conf = /etc/ceph/az1.conf
            rbd_store_pool = images
            rbd_store_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          override:
            service:
              internal:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 172.17.0.82
                spec:
                  type: LoadBalancer
          replicas: 1
          topologyRef:
            name: bzone-node-affinity
          type: edge
        az2:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends = az0:rbd,az2:rbd
            [glance_store]
            default_backend = az2
            [az0]
            rbd_store_ceph_conf = /etc/ceph/az0.conf
            rbd_store_pool = images
            rbd_store_user = openstack
            [az2]
            rbd_store_ceph_conf = /etc/ceph/az2.conf
            rbd_store_pool = images
            rbd_store_user = openstack
          networkAttachments:
            - storage
            - ctlplane
          override:
            service:
              internal:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 172.17.0.83
                spec:
                  type: LoadBalancer
          replicas: 1
          topologyRef:
            name: czone-node-affinity
          type: edge
  manila:
    enabled: false
  extraMounts:
    - extraVol:
        - extraVolType: Ceph
          mounts:
            - mountPath: /etc/ceph
              name: ceph
              readOnly: true
          propagation:
            - CinderBackup
            - CinderBackups
            - CinderVolume
            - GlanceAPI
          volumes:
            - name: ceph
              secret:
                secretName: ceph-conf-files
