---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../dz-storage/edpm/computes/r2

patches:
  - target:
      kind: ConfigMap
      name: nova-extra-config-az2
    patch: |-
      - op: replace
        path: /data/25-nova-extra.conf
        value: |
          [glance]
          endpoint_override = https://glance-az2-internal.openstack.svc:9292
          valid_interfaces = internal
          [cinder]
          cross_az_attach = True
          catalog_info = volumev3:cinderv3:internalURL
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: r2-compute-nodes
    patch: |-
      apiVersion: dataplane.openstack.org/v1beta1
      kind: OpenStackDataPlaneNodeSet
      metadata:
        name: r2-compute-nodes
      spec:
        nodes:
          edpm-r2-compute-1:
            $patch: delete
          r2-compute-1:
            $patch: delete
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: r2-compute-nodes
    patch: |-
      - op: remove
        path: /spec/services/14
      - op: remove
        path: /spec/services/13
      - op: add
        path: /spec/nodeTemplate/extraMounts
        value:
          - extraVolType: Ceph
            mounts:
              - mountPath: /etc/ceph
                name: ceph
                readOnly: true
            volumes:
              - name: ceph
                secret:
                  secretName: ceph-conf-files
