---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../dz-storage/edpm/computes/r0

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: r0-compute-nodes
    patch: |-
      apiVersion: dataplane.openstack.org/v1beta1
      kind: OpenStackDataPlaneNodeSet
      metadata:
        name: r0-compute-nodes
      spec:
        nodes:
          edpm-r0-compute-0:
            $patch: delete
          r0-compute-0:
            $patch: delete
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: r0-compute-nodes
    patch: |-
      - op: replace
        path: /metadata/name
        value: r0-ceph-nodes
      - op: replace
        path: /spec/services
        value:
          - bootstrap
          - download-cache
          - install-os
          - configure-network
          - validate-network
          - ceph-hci-pre
          - configure-os
          - frr
          - run-os
          - reboot-os
          - install-certs
      - op: add
        path: /spec/nodeTemplate/ansible/ansibleVars/edpm_ceph_hci_pre_enabled_services
        value:
          - ceph_mon
          - ceph_mgr
          - ceph_osd
