---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nova-ceph.yaml
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-post-ceph-values
      fieldPath: data.nova.ceph.conf
    targets:
      - select:
          kind: ConfigMap
          name: ceph-nova-az1
        fieldPaths:
          - data.03-ceph-nova\.conf
